from .temporal_analysis_report import TemporalAnalysisReport as TemporalAnalysisReport
from .temporal_ai_report import TemporalAIReport as TemporalAIReport
from .spatial_analysis_report import SpatialAnalysisReport as SpatialAnalysisReport
from .spatial_ai_report import SpatialAiReport as SpatialAiReport
